//! Handler stubs for layout.ui
//!
//! Auto-generated by Rui. Fill in handler bodies below.

/// Wire all widget signals to their handler functions.
///
/// Call this after building your UI from the .ui file.
#[allow(unused_imports)]
use gtk4::prelude::*;
use gtk4::glib;

pub fn connect_handlers(_builder: &gtk4::Builder) {
    // No interactive widgets with signals found in the .ui file.
}
