//! Handler stubs for layout.ui
//!
//! Auto-generated by Rui. Fill in the handler bodies below.
//! Re-running "Generate All Handlers" will NOT overwrite
//! existing handler functions — only missing ones are appended.

use gtk4::prelude::*;
use gtk4::{AlertDialog, Button};

/// Wire all widget signals to their handler functions.
///
/// Call this after building your UI from the .ui file.
/// You will need to obtain references to each widget
/// (e.g. via `builder.object::<Button>("id")`).
pub fn connect_handlers(builder: &gtk4::Builder) {
    if let Some(w) = builder.object::<Button>("click_me") {
        w.connect_clicked(move |button| {
    let dialog = AlertDialog::builder()
        .message("Hello from Rui!")
        .detail("You clicked the button. Your primitive IDE works.")
        .modal(true)
        .build();

    // Show it parented to the button's root window
    let window = button.root().and_then(|r| r.downcast::<gtk4::Window>().ok());
    dialog.show(window.as_ref());
        });
    }

}

/// Handler for GtkButton (id="click_me") — signal "clicked"
fn on_click_me_clicked(widget: &Button) {
    // TODO: implement handler
}

