//! Handler stubs for test.ui
//!
//! Auto-generated by Rui. Fill in the handler bodies below.
//! Re-running "Generate All Handlers" will NOT overwrite
//! existing handler functions — only missing ones are appended.

use gtk4::prelude::*;
use gtk4::{Button, CheckButton, DropDown, Expander, Scale, SearchEntry, SpinButton, ToggleButton};
use gtk4::prelude::*;
use gtk4::{AlertDialog, Button};

/// Wire all widget signals to their handler functions.
///
/// Call this after building your UI from the .ui file.
/// You will need to obtain references to each widget
/// (e.g. via `builder.object::<Button>("id")`).
pub fn connect_handlers(builder: &gtk4::Builder) {
    // TODO: obtain a reference to the anonymous Button and connect:
    // widget.connect_clicked(move |button| {
    //     on_button_clicked(…);
    // });

    // TODO: obtain a reference to the anonymous ToggleButton and connect:
    // widget.connect_toggled(move |button| {
    //     on_toggle_button_toggled(…);
    // });

    // TODO: obtain a reference to the anonymous Button and connect:
    // widget.connect_clicked(move |button| {
    //     on_button_clicked_2(…);
    // });

    // TODO: obtain a reference to the anonymous SearchEntry and connect:
    // widget.connect_activate(move |entry| {
    //     on_search_entry_activate(…);
    // });

    // TODO: obtain a reference to the anonymous SpinButton and connect:
    // widget.connect_value_changed(move |spin| {
    //     on_spin_button_value(…);
    // });

    // TODO: obtain a reference to the anonymous SpinButton and connect:
    // widget.connect_value_changed(move |spin| {
    //     on_spin_button_value_2(…);
    // });

    // TODO: obtain a reference to the anonymous Scale and connect:
    // widget.connect_value_changed(move |range| {
    //     on_scale_value(…);
    // });

    // TODO: obtain a reference to the anonymous Expander and connect:
    // widget.connect_expanded_notify(move |expander| {
    //     on_expander_notify::expanded(…);
    // });

    // TODO: obtain a reference to the anonymous CheckButton and connect:
    // widget.connect_toggled(move |button| {
    //     on_check_button_toggled(…);
    // });

    // TODO: obtain a reference to the anonymous CheckButton and connect:
    // widget.connect_toggled(move |button| {
    //     on_check_button_toggled_2(…);
    // });

    // TODO: obtain a reference to the anonymous DropDown and connect:
    // widget.connect_selected_notify(move |dropdown| {
    //     on_drop_down_notify::selected(…);
    // });

    // TODO: obtain a reference to the anonymous Button and connect:
    // widget.connect_clicked(move |button| {
    //     on_button_clicked_3(…);
    // });

    // TODO: obtain a reference to the anonymous Button and connect:
    // widget.connect_clicked(move |button| {
    //     on_button_clicked_4(…);
    // });

    // TODO: obtain a reference to the anonymous Button and connect:
    // widget.connect_clicked(move |button| {
    //     on_button_clicked_5(…);
    // });

    // TODO: obtain a reference to the anonymous Button and connect:
    // widget.connect_clicked(move |button| {
    //     on_button_clicked_6(…);
    // });

    // TODO: obtain a reference to the anonymous Button and connect:
    // widget.connect_clicked(move |button| {
    //     on_button_clicked_7(…);
    // });

}

/// Handler for GtkButton — signal "clicked"
fn on_button_clicked(widget: &Button) {
    // TODO: implement handler
}

/// Handler for GtkToggleButton — signal "toggled"
fn on_toggle_button_toggled(widget: &ToggleButton) {
    // TODO: implement handler
}

/// Handler for GtkButton — signal "clicked"
fn on_button_clicked_2(widget: &Button) {
    // TODO: implement handler
}

/// Handler for GtkSearchEntry — signal "activate"
fn on_search_entry_activate(widget: &SearchEntry) {
    // TODO: implement handler
}

/// Handler for GtkSpinButton — signal "value-changed"
fn on_spin_button_value(widget: &SpinButton) {
    // TODO: implement handler
}

/// Handler for GtkSpinButton — signal "value-changed"
fn on_spin_button_value_2(widget: &SpinButton) {
    // TODO: implement handler
}

/// Handler for GtkScale — signal "value-changed"
fn on_scale_value(widget: &Scale) {
    // TODO: implement handler
}

/// Handler for GtkExpander — signal "notify::expanded"
fn on_expander_notify::expanded(widget: &Expander) {
    // TODO: implement handler
}

/// Handler for GtkCheckButton — signal "toggled"
fn on_check_button_toggled(widget: &CheckButton) {
    // TODO: implement handler
}

/// Handler for GtkCheckButton — signal "toggled"
fn on_check_button_toggled_2(widget: &CheckButton) {
    // TODO: implement handler
}

/// Handler for GtkDropDown — signal "notify::selected"
fn on_drop_down_notify::selected(widget: &DropDown) {
    // TODO: implement handler
}

/// Handler for GtkButton — signal "clicked"
fn on_button_clicked_3(widget: &Button) {
    // TODO: implement handler
}

/// Handler for GtkButton — signal "clicked"
fn on_button_clicked_4(widget: &Button) {
    // TODO: implement handler
}

/// Handler for GtkButton — signal "clicked"
fn on_button_clicked_5(widget: &Button) {
    // TODO: implement handler
}

/// Handler for GtkButton — signal "clicked"
fn on_button_clicked_6(widget: &Button) {
    // TODO: implement handler
}

/// Handler for GtkButton — signal "clicked"
fn on_button_clicked_7(widget: &Button) {
    // TODO: implement handler
        let dialog = AlertDialog::builder()
        .message("Hello from Rui!")
        .detail("You clicked the button. Your primitive IDE works.")
        .modal(true)
        .build();

    // Show it parented to the button's root window
    let window = button.root().and_then(|r| r.downcast::<gtk4::Window>().ok());
    dialog.show(window.as_ref());
}
    
}
