//! Handler stubs for layout.ui
//!
//! Auto-generated by Rui. Fill in the handler bodies below.
//! Re-running "Generate All Handlers" will NOT overwrite
//! existing handler functions — only missing ones are appended.

#[allow(unused_imports)]
use gtk4::prelude::*;
use gtk4::{Button, Notebook, ToggleButton};

/// Wire all widget signals to their handler functions.
///
/// Call this after building your UI from the .ui file.
/// You will need to obtain references to each widget
/// (e.g. via `builder.object::<Button>("id")`).
pub fn connect_handlers(builder: &gtk4::Builder) {
    if let Some(w) = builder.object::<ToggleButton>("btn_design") {
        w.connect_toggled(move |button| {
            on_btn_design_toggled(&w);
        });
    }

    if let Some(w) = builder.object::<ToggleButton>("btn_code") {
        w.connect_toggled(move |button| {
            on_btn_code_toggled(&w);
        });
    }

    if let Some(w) = builder.object::<Notebook>("left_nb") {
        w.connect_switch_page(move |notebook, _page, page_num| {
            on_left_nb_switch(&w);
        });
    }

    if let Some(w) = builder.object::<Button>("btn_new_project") {
        w.connect_clicked(move |button| {
            on_btn_new_project_clicked(&w);
        });
    }

    if let Some(w) = builder.object::<Button>("btn_open_project") {
        w.connect_clicked(move |button| {
            on_btn_open_project_clicked(&w);
        });
    }

    if let Some(w) = builder.object::<Button>("btn_save_all") {
        w.connect_clicked(move |button| {
            on_btn_save_all_clicked(&w);
        });
    }

    if let Some(w) = builder.object::<Notebook>("center_nb") {
        w.connect_switch_page(move |notebook, _page, page_num| {
            on_center_nb_switch(&w);
        });
    }

    if let Some(w) = builder.object::<Button>("btn_close_output") {
        w.connect_clicked(move |button| {
            on_btn_close_output_clicked(&w);
        });
    }

    if let Some(w) = builder.object::<Notebook>("right_nb") {
        w.connect_switch_page(move |notebook, _page, page_num| {
            on_right_nb_switch(&w);
        });
    }

}

/// Handler for GtkToggleButton (id="btn_design") — signal "toggled"
fn on_btn_design_toggled(widget: &gtk4::ToggleButton) {
    // TODO: implement handler
}

/// Handler for GtkToggleButton (id="btn_code") — signal "toggled"
fn on_btn_code_toggled(widget: &gtk4::ToggleButton) {
    // TODO: implement handler
}

/// Handler for GtkNotebook (id="left_nb") — signal "switch-page"
fn on_left_nb_switch(widget: &gtk4::Notebook) {
    // TODO: implement handler
}

/// Handler for GtkButton (id="btn_new_project") — signal "clicked"
fn on_btn_new_project_clicked(widget: &gtk4::Button) {
    // TODO: implement handler
}

/// Handler for GtkButton (id="btn_open_project") — signal "clicked"
fn on_btn_open_project_clicked(widget: &gtk4::Button) {
    // TODO: implement handler
}

/// Handler for GtkButton (id="btn_save_all") — signal "clicked"
fn on_btn_save_all_clicked(widget: &gtk4::Button) {
    // TODO: implement handler
}

/// Handler for GtkNotebook (id="center_nb") — signal "switch-page"
fn on_center_nb_switch(widget: &gtk4::Notebook) {
    // TODO: implement handler
}

/// Handler for GtkButton (id="btn_close_output") — signal "clicked"
fn on_btn_close_output_clicked(widget: &gtk4::Button) {
    // TODO: implement handler
}

/// Handler for GtkNotebook (id="right_nb") — signal "switch-page"
fn on_right_nb_switch(widget: &gtk4::Notebook) {
    // TODO: implement handler
}

